{% set name = "pypcd4" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypcd4-{{ version }}.tar.gz
  sha256: dae09e3ef475a8b30ef8888e9feaf82f479759c421cb56c6533a006981b48c27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21.0
    - python-neo-lzf >=0.3.5
    - pydantic >=1.10.8,<3.0.0

test:
  imports:
    - pypcd4
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Read and write PCL .pcd files in python
  home: https://github.com/MapIV/pypcd4
  license: BSD-3-Clause
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - tetov
